<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_5db35ce3c77d6',
		'title' => 'Single',
		'fields' => array(
			array(
				'key' => 'field_5db73c5ce7674',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Recommended dimensions are 1440 x 1440',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => 1440,
				'min_height' => 1440,
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5db73c44e7671',
				'label' => 'Subheading',
				'name' => 'subheading',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5db73c4ae7672',
				'label' => 'Heading',
				'name' => 'heading',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5db73c4fe7673',
				'label' => 'Text',
				'name' => 'single_text',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5db363411c008',
				'label' => 'Work Groups',
				'name' => 'work_groups',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Work Group',
				'sub_fields' => array(
					array(
						'key' => 'field_5db363b79b2a8',
						'label' => 'Heading',
						'name' => 'heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5db360d919c02',
						'label' => 'Work',
						'name' => 'work',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => 'Add Work',
						'sub_fields' => array(
							array(
								'key' => 'field_5db3610e19c03',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'image' => 'Image',
									'audio' => 'Audio',
									'video' => 'Video',
								),
								'default_value' => array(
									0 => 'image',
								),
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5db3613219c04',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => 'Recommended dimensions are 720 x 405',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5db3610e19c03',
											'operator' => '==',
											'value' => 'image',
										),
									),
									array(
										array(
											'field' => 'field_5db3610e19c03',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => 720,
								'min_height' => 405,
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5db3615819c05',
								'label' => 'Images',
								'name' => 'images',
								'type' => 'gallery',
								'instructions' => 'Recommended dimensions are 1920 x 1080',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5db3610e19c03',
											'operator' => '==',
											'value' => 'image',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'insert' => 'append',
								'library' => 'all',
								'min_width' => 1920,
								'min_height' => 1080,
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5db361fc19c07',
								'label' => 'Thumbnail Image',
								'name' => 'thumbnail_image',
								'type' => 'image',
								'instructions' => 'Recommended dimensions are 150 x 150',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5db3610e19c03',
											'operator' => '==',
											'value' => 'audio',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => 150,
								'min_height' => 150,
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5db361b819c06',
								'label' => 'Audio',
								'name' => 'audio',
								'type' => 'file',
								'instructions' => 'Allowed file types are MP3 and WAV',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5db3610e19c03',
											'operator' => '==',
											'value' => 'audio',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'library' => 'all',
								'min_size' => '',
								'max_size' => '',
								'mime_types' => 'mp3, wav',
							),
							array(
								'key' => 'field_5db3622419c08',
								'label' => 'Video',
								'name' => 'video',
								'type' => 'oembed',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5db3610e19c03',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'width' => '',
								'height' => '',
							),
							array(
								'key' => 'field_5db3625119c09',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'textarea',
								'instructions' => 'Recommended length is 120 characters',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => 4,
								'new_lines' => '',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'work',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
            1 => 'excerpt',
            2 => 'discussion',
            3 => 'comments',
            4 => 'featured_image',
            5 => 'slug',
            6 => 'author',
        ),
        'active' => true,
        'description' => '',
	));

    acf_add_local_field_group(array(
        'key' => 'group_5d9ce61wut65e',
        'title' => 'Index',
        'fields' => array(
			array(
				'key' => 'field_wz5fp4woxi93f',
				'label' => 'Type',
				'name' => 'type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'image' => 'Image',
					'audio' => 'Audio',
					'video' => 'Video',
				),
				'default_value' => array(
					0 => 'image',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
            array(
                'key' => 'field_sn5p8bvl1b4p3',
                'label' => 'Featured Image',
                'name' => 'featured_image',
                'type' => 'image',
                'instructions' => 'Recommended dimensions are 1440 x 810',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => 1440,
                'min_height' => 810,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5d9ce61abc844',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => 'Recommended dimensions are 720 x 405',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => 720,
                'min_height' => 405,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5d9ce6a5bc846',
                'label' => 'Audio',
                'name' => 'audio',
                'type' => 'file',
                'instructions' => 'Allowed file types are MP3 and WAV',
                'required' => 0,
                'conditional_logic' => array(
					array(
						array(
							'field' => 'field_wz5fp4woxi93f',
							'operator' => '==',
							'value' => 'audio',
						),
					),
				),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'mp3, wav',
            ),
            array(
                'key' => 'field_5d9ce652bc845',
                'label' => 'Video',
                'name' => 'video',
                'type' => 'oembed',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
					array(
						array(
							'field' => 'field_wz5fp4woxi93f',
							'operator' => '==',
							'value' => 'video',
						),
					),
				),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'width' => '320',
                'height' => '195',
			),
			array(
                'key' => 'field_5d9ce7a5bc847',
                'label' => 'Text',
                'name' => 'text',
                'type' => 'textarea',
                'instructions' => 'Recommended length is 120 characters',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'work',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
            1 => 'excerpt',
            2 => 'discussion',
            3 => 'comments',
            4 => 'featured_image',
            5 => 'slug',
            6 => 'author',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
