module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    colors: {
      transparent: 'transparent',
      black: '#161616',
      white: '#fff',
      pink: '#db3053',
      purple: '#161c58',
      teal: '#0c8483',
      blue: {
        light: '#65bdff',
        link: '#0a6eb9',
        default: '#242c70',
      },
      gray: {
        a11y: '#707070',
        border: '#c4c4c4',
        default: '#f4f4f4',
      },
    },
    spacing: {
      px: '1px',
      '0': '0',
      '5': '0.3125rem',
      '10': '0.625rem',
      '15': '0.9375rem',
      '20': '1.25rem',
      '25': '1.5625rem',
      '30': '1.875rem',
      '40': '2.5rem',
      '50': '3.125rem',
      '60': '3.75rem',
      '75': '4.6875rem',
      '100': '6.25rem',
      '150': '9.375rem',
      '200': '12.5rem',
    },
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    borderColor: theme => ({
      ...theme('colors'),
      default: theme('colors.gray.border', 'currentColor'),
    }),
    borderRadius: {
      none: '0',
      full: '9999px',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
    },
    boxShadow: {
      none: 'none',
      sm: '0px 20px 30px rgba(0, 0, 0, 0.15)',
      lg: '0px 30px 40px rgba(0, 0, 0, 0.25)',
      default: '0px 30px 30px rgba(0, 0, 0, 0.15)',
    },
    container: {},
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      text: 'text',
      move: 'move',
      'not-allowed': 'not-allowed',
    },
    fill: {
      current: 'currentColor',
    },
    flex: {
      none: 'none',
      '0': '0 0 auto',
      '1': '1 1 auto',
    },
    flexGrow: {
      '0': '0',
      default: '1',
    },
    flexShrink: {
      '0': '0',
      default: '1',
    },
    fontFamily: {
      sans: ['Gotham', 'Arial', 'sans-serif'],
      serif: ['Georgia', 'Times', '"Times New Roman"', 'serif'],
    },
    fontSize: {
      '11': '0.6875rem',
      '12': '0.75rem',
      '14': '0.875rem',
      '16': '1rem',
      '18': '1.125rem',
      '20': '1.25rem',
      '22': '1.375rem',
      '24': '1.5rem',
      '30': '1.875rem',
      '36': '2.25rem',
      '42': '2.625rem',
      '48': '3rem',
      '64': '4rem',
      '88': '5.5rem',
    },
    fontWeight: {
      normal: '400',
      bold: '700',
    },
    height: theme => ({
      auto: 'auto',
      '0': '0',
      '44': '2.75rem',
      full: '100%',
      screen: '100vh',
    }),
    inset: {
      '0': '0',
      '1/2': '50%',
      auto: 'auto',
    },
    letterSpacing: {
      normal: '0',
      wide: '0.1em',
    },
    lineHeight: {
      none: '1',
      tighter: '1.2',
      tight: '1.4',
      normal: '1.6',
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    maxHeight: {
      full: '100%',
      screen: '100vh',
    },
    maxWidth: {
      '0': '0',
      none: 'none',
      full: '100%',
    },
    minHeight: {
      '0': '0',
      full: '100%',
      screen: '100vh',
    },
    minWidth: {
      '0': '0',
      full: '100%',
    },
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    opacity: {
      '0': '0',
      '25': '0.25',
      '50': '0.5',
      '75': '0.75',
      '100': '1',
    },
    order: {
      first: '-9999',
      last: '9999',
      none: '0',
    },
    padding: theme => theme('spacing'),
    stroke: {
      current: 'currentColor',
    },
    textColor: theme => theme('colors'),
    width: theme => ({
      auto: 'auto',
      '1/4': '25%',
      '1/3': '33.33333%',
      '5/12': '41.66667%',
      '1/2': '50%',
      '7/12': '58.33333%',
      '2/3': '66.66667%',
      '3/4': '75%',
      '44': '2.75rem',
      full: '100%',
      '1/2-screen': '50vw',
      screen: '100vw',
    }),
    zIndex: {
      auto: 'auto',
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
    },
  },
  variants: {
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: false,
    backgroundAttachment: false,
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: false,
    borderColor: [],
    borderRadius: [],
    borderStyle: ['responsive'],
    borderWidth: [],
    boxShadow: ['responsive', 'hover', 'focus'],
    cursor: false,
    display: ['responsive'],
    fill: [],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    fontFamily: [],
    fontSize: ['responsive'],
    fontSmoothing: false,
    fontStyle: ['responsive'],
    fontWeight: ['responsive'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: false,
    listStyleType: false,
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: false,
    objectPosition: false,
    opacity: ['responsive'],
    order: ['responsive'],
    outline: false,
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: [],
    position: ['responsive'],
    resize: false,
    stroke: false,
    tableLayout: false,
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    textDecoration: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive'],
    userSelect: false,
    verticalAlign: [],
    visibility: ['responsive'],
    whitespace: [],
    width: ['responsive'],
    wordBreak: false,
    zIndex: ['responsive'],
  },
  corePlugins: {
    container: false,
  },
  plugins: [
    require('./plugins/aspect-ratio')({
      dimensions: {
        square: [1, 1],
        '16/9': [16, 9],
      },
      variants: ['responsive'],
    }),
    require('./plugins/screen-reader')({
      variants: ['focus'],
    }),
    require('./plugins/transition')({
      transitions: {
        slow: 'all 0.4s ease',
        fast: 'all 0.2s ease',
        default: 'all 0.3s ease',
      },
    }),
    require('./plugins/translate')({
      variants: ['responsive'],
    }),
  ],
}
